### ISSUE TITLE
Feature Request: Add FAQ in documentation to enhance the user experience

### ISSUE THREAD

**Issue by adityasxna** [starknet-io/starknet-docs#1087] opened 2024-01-17 12:57 UTC
**Is your feature request related to a problem? Please describe.**
Add FAQ in the Documentation it enhance the user experience

**Comment by stoobie** [comment] 2024-01-18 13:54
I'm closing this as it is a duplicate of #1088 .

**Closed by stoobie** 2024-01-18 13:54 UTC
Labels: enhancement
